In [1]:
import pandas as pd

In [2]:
data_df = pd.read_csv("DOB_Job_Application_Filings_NB.csv", sep = ',', engine = 'python')

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
data_df.head()

,Job #,Doc #,Borough,House #,Street Name,Block,Lot,Bin #,Job Type,Job Status,Job Status Descrp,Latest Action Date,Building Type,Community - Board,Cluster,Landmarked,Adult Estab,Loft Board,City Owned,Little e,PC Filed,eFiling Filed,Plumbing,Mechanical,Boiler,Fuel Burning,Fuel Storage,Standpipe,Sprinkler,Fire Alarm,Equipment,Fire Suppression,Curb Cut,Other,Other Description,Applicant's First Name,Applicant's Last Name,Applicant Professional Title,Applicant License #,Professional Cert,Pre- Filing Date,Paid,Fully Paid,Assigned,Approved,Fully Permitted,Initial Cost,Total Est. Fee,Fee Status,Existing Zoning Sqft,Proposed Zoning Sqft,Horizontal Enlrgmt,Vertical Enlrgmt,Enlargement SQ Footage,Street Frontage,ExistingNo. of Stories,Proposed No. of Stories,Existing Height,Proposed Height,Existing Dwelling Units,Proposed Dwelling Units,Existing Occupancy,Proposed Occupancy,Site Fill,Zoning Dist1,Zoning Dist2,Zoning Dist3,Special District 1,Special District 2,Owner Type,Non-Profit,Owner's First Name,Owner's Last Name,Owner's Business Name,Owner's House Number,Owner'sHouse Street Name,City,State,Zip,Owner'sPhone #,Job Description,DOBRunDate,JOB_S1_NO,TOTAL_CONSTRUCTION_FLOOR_AREA,WITHDRAWAL_FLAG,SIGNOFF_DATE,SPECIAL_ACTION_STATUS,SPECIAL_ACTION_DATE,BUILDING_CLASS,JOB_NO_GOOD_COUNT,GIS_LATITUDE,GIS_LONGITUDE,GIS_COUNCIL_DISTRICT,GIS_CENSUS_TRACT,GIS_NTA_NAME,GIS_BIN
0,220538611,1,BRONX,915,ELSMERE PL,2985,64,2130498,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/05/2021,OTHERS,206,N,N,N,N,NaN,Y,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,X,GEN. CONSTR.,MINKUK,KIM,RA,32897,N,06/24/2016,06/24/2016,06/24/2016,11/27/2018,05/11/2020,04/29/2021,$0.00,$29234.50,STANDARD,0,49075,NaN,NaN,0,0,0,9,0,90,NaN,72.0,NaN,R-2,ON-SITE,R7-1,NaN,NaN,NaN,NaN,CORPORATION,N,JAY,MARTINO,STAGG GROUP,NaN,NaN,NaN,NaN,NaN,9146687511,ERECTION OF 9 STORY RESIDENTIAL BUILDING.,11/23/2021 00:00:00,2637000,64610,0,NaN,N,NaN,D7,0,40.841590,-73.885100,17.0,359.0,East Tremont,2000000.0
1,220152803,1,BRONX,1325,SOUTHERN BOULEVARD,2976,98,2010494,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/15/2021,OTHERS,203,N,N,N,N,NaN,N,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,X,GEN. CONSTR.,SUZANNA,THARIAN,RA,29684,N,06/19/2017,06/20/2017,06/20/2017,06/29/2017,10/18/2017,03/07/2019,$0.00,$11245.62,STANDARD,0,34363,NaN,NaN,0,0,0,8,0,85,NaN,31.0,NaN,R-2,ON-SITE,R7-1,NaN,NaN,NaN,NaN,CORPORATION,N,NORBERTO,VELAZQUEZ,1319-25 SOUTHERN BLVD LLC,NaN,NaN,NaN,NaN,NaN,3475655481,NaN,11/16/2021 00:00:00,2802048,42672,0,NaN,N,NaN,D7,0,40.831084,-73.891496,17.0,123.0,Crotona Park East,2010494.0
2,220649706,1,BRONX,3923,CARPENTER AVE,4819,13,2130529,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,04/29/2021,OTHERS,212,N,N,N,N,NaN,N,NaN,Y,X,X,X,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,X,GEN. CONSTR.,JULIO,LEDER-LUIS,RA,20478,N,06/19/2018,06/19/2018,06/19/2018,07/23/2020,08/11/2020,03/16/2021,$0.00,$11043.00,STANDARD,0,20237,NaN,NaN,0,0,0,7,0,65,NaN,27.0,NaN,R-2,USE UNDER 300 CU.YD,R7-1,NaN,NaN,NaN,NaN,INDIVIDUAL,N,ROBERT,LUMAJ,ATLANTIS RENOVATIONS INC,NaN,NaN,NaN,NaN,NaN,3476210292,NaN,04/30/2021 00:00:00,2965629,24540,0,NaN,N,NaN,V0,0,40.887420,-73.864069,12.0,394.0,Williamsbridge-Olinville,2062827.0
3,121205604,1,MANHATTAN,270,PARK AVENUE,1283,21,1035421,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/30/2021,OTHERS,105,N,N,N,N,NaN,N,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,GEN. CONSTR.,NICKOLAS,ZIGOMANIS,RA,33081,N,06/26/2019,06/26/2019,06/26/2019,12/05/2019,09/02/2021,11/30/2021,$0.00,$1100447.10,STANDARD,0,1864801,NaN,NaN,0,0,0,57,0,1388,NaN,NaN,NaN,B,USE UNDER 300 CU.YD,C5-3,NaN,NaN,MID,NaN,CORPORATION,N,DEVIN,MAHER,"JP MORGAN AND CHASE BANK, N.A.",NaN,NaN,NaN,NaN,NaN,2122704958,NaN,12/09/2021 00:00:00,3126397,2498577,0,NaN,N,NaN,O4,0,40.755641,-73.975109,4.0,94.0,Midtown-Midtown South,1035421.0
4,321597795,1,BROOKLYN,963,ATLANTIC AVENUE,2019,80,3335119,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,06/22/2021,OTHERS,302,N,N,N,N,NaN,Y,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,GEN. CONSTR.,DANIEL,BERNSTEIN,RA,16854,N,09/16/2019,09/18/2019,09/18/2019,04/08/2021,06/21/2021,06/22/2021,$0.00,$53841.60,STANDARD,0,88368,NaN,NaN,0,0,0,9,0,95,NaN,124.0,NaN,R-2,ON-SITE,R7A,NaN,NaN,NaN,NaN,CORPORATION,N,EFRAIM,WEBER,86 LEFFERTS CORP,NaN,NaN,NaN,NaN,NaN,9176824871,NaN,10/12/2021 00:00:00,3158207,119648,0,NaN,N,NaN,D6,0,40.680263,-73.960337,36.0,227.0,Clinton Hill,3335119.0

In [5]:
df = data_df.drop(columns=['Doc #',
'Block',
"Lot",
'Bin #',
'Cluster',
'Landmarked',
'Adult Estab',
'Loft Board',
'City Owned',
'Little e',
'PC Filed', 
'eFiling Filed',
'Plumbing',
'Mechanical',
'Boiler',
'Fuel Burning',
'Fuel Storage',
'Standpipe',
'Sprinkler',
'Fire Alarm',
'Equipment',
'Fire Suppression',
'Curb Cut',
'Other',
'Other Description',
'Pre- Filing Date',
'Paid',
'Fully Paid',
'Assigned',
'Approved',
'Initial Cost',
'Total Est. Fee',
'Fee Status',
'Horizontal Enlrgmt',
'Vertical Enlrgmt',
'Enlargement SQ Footage',
'Street Frontage',
'Existing Dwelling Units',
'Proposed Dwelling Units',
'Existing Occupancy',
'Proposed Occupancy',
'Site Fill',
'Zoning Dist1',
'Zoning Dist2',
'Zoning Dist3',
'Special District 1',
'Special District 2',
'Owner Type',
'Non-Profit',
"Owner's House Number",
"Owner'sHouse Street Name",
'State',
'Zip',
'TOTAL_CONSTRUCTION_FLOOR_AREA',
'WITHDRAWAL_FLAG',
'SIGNOFF_DATE',
'SPECIAL_ACTION_STATUS',
'SPECIAL_ACTION_DATE',
'BUILDING_CLASS',
'JOB_NO_GOOD_COUNT',
'GIS_COUNCIL_DISTRICT',
'GIS_CENSUS_TRACT',
'GIS_BIN'])

In [6]:
df.head()

,Job #,Borough,House #,Street Name,Job Type,Job Status,Job Status Descrp,Latest Action Date,Building Type,Community - Board,Applicant's First Name,Applicant's Last Name,Applicant Professional Title,Applicant License #,Professional Cert,Fully Permitted,Existing Zoning Sqft,Proposed Zoning Sqft,ExistingNo. of Stories,Proposed No. of Stories,Existing Height,Proposed Height,Owner's First Name,Owner's Last Name,Owner's Business Name,City,Owner'sPhone #,Job Description,DOBRunDate,JOB_S1_NO,GIS_LATITUDE,GIS_LONGITUDE,GIS_NTA_NAME
0,220538611,BRONX,915,ELSMERE PL,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/05/2021,OTHERS,206,MINKUK,KIM,RA,32897,N,04/29/2021,0,49075,0,9,0,90,JAY,MARTINO,STAGG GROUP,NaN,9146687511,ERECTION OF 9 STORY RESIDENTIAL BUILDING.,11/23/2021 00:00:00,2637000,40.841590,-73.885100,East Tremont
1,220152803,BRONX,1325,SOUTHERN BOULEVARD,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/15/2021,OTHERS,203,SUZANNA,THARIAN,RA,29684,N,03/07/2019,0,34363,0,8,0,85,NORBERTO,VELAZQUEZ,1319-25 SOUTHERN BLVD LLC,NaN,3475655481,NaN,11/16/2021 00:00:00,2802048,40.831084,-73.891496,Crotona Park East
2,220649706,BRONX,3923,CARPENTER AVE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,04/29/2021,OTHERS,212,JULIO,LEDER-LUIS,RA,20478,N,03/16/2021,0,20237,0,7,0,65,ROBERT,LUMAJ,ATLANTIS RENOVATIONS INC,NaN,3476210292,NaN,04/30/2021 00:00:00,2965629,40.887420,-73.864069,Williamsbridge-Olinville
3,121205604,MANHATTAN,270,PARK AVENUE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/30/2021,OTHERS,105,NICKOLAS,ZIGOMANIS,RA,33081,N,11/30/2021,0,1864801,0,57,0,1388,DEVIN,MAHER,"JP MORGAN AND CHASE BANK, N.A.",NaN,2122704958,NaN,12/09/2021 00:00:00,3126397,40.755641,-73.975109,Midtown-Midtown South
4,321597795,BROOKLYN,963,ATLANTIC AVENUE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,06/22/2021,OTHERS,302,DANIEL,BERNSTEIN,RA,16854,N,06/22/2021,0,88368,0,9,0,95,EFRAIM,WEBER,86 LEFFERTS CORP,NaN,9176824871,NaN,10/12/2021 00:00:00,3158207,40.680263,-73.960337,Clinton Hill

In [7]:
df['Fully Permitted'].isnull().values.any()

False

In [8]:
df = df.dropna(subset=['Fully Permitted'])

In [9]:
df['Fully Permitted'].isnull().values.any()

False

In [10]:
df['Fully Permitted'] = pd.to_datetime(df['Fully Permitted'], errors ="coerce", infer_datetime_format=True)

In [11]:
df['Fully Permitted'].iloc[1:100]

1    2019-03-07
2    2021-03-16
3    2021-11-30
4    2021-06-22
5    2021-05-05
6    2021-10-14
7    2021-08-30
8    2019-02-11
9    2021-11-09
10   2021-04-30
11   2021-08-26
12   2021-12-09
13   2021-11-17
14   2021-10-06
15   2021-08-18
16   2020-12-21
17   2021-07-29
18   2021-05-03
19   2019-12-03
20   2021-09-15
21   2021-09-16
22   2020-05-20
23   2021-05-11
24   2021-12-30
25   2019-01-07
26   2019-01-29
27   2019-08-20
28   2021-02-28
29   2020-08-26
30   2021-02-18
31   2021-07-13
32   2021-10-01
33   2019-01-22
34   2021-05-06
35   2019-11-21
36   2020-04-17
37   2019-12-10
38   2019-08-08
39   2021-06-29
40   2021-05-05
41   2021-06-25
42   2021-09-14
43   2021-12-17
44   2021-05-28
45   2021-08-16
46   2019-08-19
47   2019-12-04
48   2021-08-06
49   2021-11-12
50   2019-09-17
51   2021-07-16
52   2021-08-25
53   2019-03-29
54   2021-05-10
55   2019-06-04
56   2021-11-23
57   2020-03-26
58   2021-04-13
59   2019-11-21
60   2021-05-05
61   2019-06-03
62   2020-11-12
63   2019-09-05
64   2021-11-24
65   2021-04-02
66   2021-11-04
67   2021-07-13
68   2021-07-28
69   2021-12-23
70   2019-04-01
71   2019-07-09
72   2020-10-26
73   2021-10-25
74   2021-12-07
75   2019-08-13
76   2020-05-04
77   2019-09-13
78   2021-05-12
79   2020-09-01
80   2021-05-18
81   2021-05-18
82   2021-08-13
83   2020-01-07
84   2021-08-04
85   2020-12-23
86   2021-05-20
87   2020-07-29
88   2019-12-02
89   2021-12-17
90   2021-07-22
91   2021-05-21
92   2021-05-21
93   2019-05-03
94   2019-08-02
95   2019-01-11
96   2019-04-09
97   2020-08-14
98   2021-05-24
99   2020-09-18
Name: Fully Permitted, dtype: datetime64[ns]

In [12]:
df['Fully Permitted'].iloc[1:1000]

1     2019-03-07
2     2021-03-16
3     2021-11-30
4     2021-06-22
5     2021-05-05
6     2021-10-14
7     2021-08-30
8     2019-02-11
9     2021-11-09
10    2021-04-30
11    2021-08-26
12    2021-12-09
13    2021-11-17
14    2021-10-06
15    2021-08-18
16    2020-12-21
17    2021-07-29
18    2021-05-03
19    2019-12-03
20    2021-09-15
21    2021-09-16
22    2020-05-20
23    2021-05-11
24    2021-12-30
25    2019-01-07
26    2019-01-29
27    2019-08-20
28    2021-02-28
29    2020-08-26
30    2021-02-18
31    2021-07-13
32    2021-10-01
33    2019-01-22
34    2021-05-06
35    2019-11-21
36    2020-04-17
37    2019-12-10
38    2019-08-08
39    2021-06-29
40    2021-05-05
41    2021-06-25
42    2021-09-14
43    2021-12-17
44    2021-05-28
45    2021-08-16
46    2019-08-19
47    2019-12-04
48    2021-08-06
49    2021-11-12
50    2019-09-17
51    2021-07-16
52    2021-08-25
53    2019-03-29
54    2021-05-10
55    2019-06-04
56    2021-11-23
57    2020-03-26
58    2021-04-13
59    2019-11-21
60    2021-05-05
61    2019-06-03
62    2020-11-12
63    2019-09-05
64    2021-11-24
65    2021-04-02
66    2021-11-04
67    2021-07-13
68    2021-07-28
69    2021-12-23
70    2019-04-01
71    2019-07-09
72    2020-10-26
73    2021-10-25
74    2021-12-07
75    2019-08-13
76    2020-05-04
77    2019-09-13
78    2021-05-12
79    2020-09-01
80    2021-05-18
81    2021-05-18
82    2021-08-13
83    2020-01-07
84    2021-08-04
85    2020-12-23
86    2021-05-20
87    2020-07-29
88    2019-12-02
89    2021-12-17
90    2021-07-22
91    2021-05-21
92    2021-05-21
93    2019-05-03
94    2019-08-02
95    2019-01-11
96    2019-04-09
97    2020-08-14
98    2021-05-24
99    2020-09-18
100   2019-10-08
101   2019-05-22
102   2020-10-30
103   2021-05-26
104   2021-08-30
105   2020-06-22
106   2021-04-26
107   2019-04-04
108   2021-02-05
109   2021-05-28
110   2021-05-28
111   2020-04-14
112   2020-02-06
113   2020-05-21
114   2020-03-19
115   2020-07-21
116   2020-09-25
117   2020-09-09
118   2021-06-01
119   2021-09-15
120   2021-11-17
121   2019-10-30
122   2019-12-12
123   2019-06-20
124   2019-05-13
125   2020-09-03
126   2021-11-17
127   2021-06-25
128   2021-01-20
129   2019-11-06
130   2019-11-14
131   2020-07-24
132   2021-05-18
133   2020-02-18
134   2019-09-23
135   2020-07-27
136   2021-11-30
137   2021-09-16
138   2019-11-15
139   2019-05-30
140   2020-10-28
141   2019-05-24
142   2021-07-28
143   2019-03-06
144   2019-06-20
145   2020-06-10
146   2020-11-09
147   2021-06-08
148   2020-11-03
149   2021-04-26
150   2019-01-07
151   2020-03-03
152   2021-03-03
153   2020-01-09
154   2019-07-26
155   2021-06-10
156   2020-07-09
157   2019-08-02
158   2019-03-28
159   2021-08-03
160   2021-06-11
161   2019-05-16
162   2021-06-15
163   2019-09-12
164   2019-02-01
165   2019-01-15
166   2019-07-02
167   2019-08-13
168   2019-08-20
169   2019-07-17
170   2019-04-23
171   2021-04-02
172   2019-08-01
173   2020-06-08
174   2020-06-08
175   2021-02-05
176   2021-09-20
177   2021-03-02
178   2020-12-14
179   2020-08-18
180   2019-05-15
181   2019-12-23
182   2020-03-04
183   2020-12-07
184   2021-08-30
185   2021-11-01
186   2021-02-22
187   2020-07-29
188   2021-11-16
189   2019-01-02
190   2019-05-17
191   2020-01-29
192   2021-06-30
193   2021-06-30
194   2019-04-11
195   2019-11-18
196   2019-10-25
197   2020-10-29
198   2020-04-02
199   2019-07-10
200   2019-06-14
201   2019-09-03
202   2019-09-11
203   2019-11-08
204   2019-04-02
205   2021-02-11
206   2020-06-26
207   2019-01-22
208   2019-09-05
209   2020-11-28
210   2019-01-17
211   2019-01-31
212   2019-05-29
213   2019-08-30
214   2019-04-12
215   2019-10-31
216   2019-01-09
217   2019-06-05
218   2019-02-14
219   2019-06-14
220   2020-03-12
221   2021-10-15
222   2021-07-08
223   2021-04-19
224   2020-11-10
225   2020-08-05
226   2020-12-30
227   2021-11-16
228   2021-07-14
229   2021-08-16
230   2019-12-26
231   2019-07-30
232   2021-07-16
233   2021-03-03
234   2021-07-16
235   2020-06-27
236   2021-12-17
237   2020-02-12
238   2021-02-01
239   2021-03-10
240   2021-03-18
241   2021-10-15
242   2021-07-20
243   2021-08-12
244   2019-07-01
245   2021-03-17
246   2020-12-15
247   2021-02-26
248   2021-07-28
249   2021-11-08
250   2019-04-11
251   2021-01-05
252   2020-02-04
253   2020-08-24
254   2019-04-05
255   2019-08-06
256   2020-06-12
257   2021-03-10
258   2019-04-30
259   2020-02-06
260   2019-06-19
261   2019-08-27
262   2019-11-01
263   2020-07-13
264   2019-09-10
265   2019-02-05
266   2019-10-30
267   2020-07-30
268   2020-09-11
269   2020-10-14
270   2019-01-11
271   2019-03-13
272   2020-12-29
273   2021-08-11
274   2019-08-01
275   2019-06-12
276   2019-02-06
277   2019-04-08
278   2021-07-07
279   2020-10-17
280   2021-08-17
281   2021-08-17
282   2019-03-19
283   2021-08-19
284   2021-08-19
285   2019-10-16
286   2021-07-29
287   2021-10-12
288   2020-12-05
289   2021-09-23
290   2021-08-24
291   2021-12-23
292   2019-10-31
293   2019-05-24
294   2019-08-30
295   2019-04-04
296   2019-09-16
297   2019-01-07
298   2021-09-01
299   2019-04-09
300   2019-07-11
301   2021-01-21
302   2019-04-24
303   2020-06-22
304   2020-09-22
305   2021-01-22
306   2021-01-06
307   2020-06-11
308   2020-10-08
309   2020-02-12
310   2020-12-29
311   2019-05-15
312   2019-11-26
313   2020-09-14
314   2020-07-27
315   2020-07-02
316   2019-05-31
317   2020-02-26
318   2020-07-13
319   2021-10-15
320   2019-09-16
321   2019-01-15
322   2020-08-05
323   2021-10-04
324   2021-05-26
325   2021-02-17
326   2020-12-04
327   2020-07-21
328   2019-07-17
329   2019-05-15
330   2020-12-05
331   2021-04-13
332   2020-07-31
333   2021-06-25
334   2021-10-21
335   2019-04-25
336   2019-12-30
337   2021-12-29
338   2019-06-21
339   2019-05-29
340   2019-10-24
341   2019-04-10
342   2020-06-24
343   2019-01-16
344   2019-09-27
345   2019-09-13
346   2019-07-17
347   2019-01-30
348   2021-01-12
349   2019-04-22
350   2019-09-23
351   2019-05-09
352   2021-11-30
353   2019-12-24
354   2021-12-02
355   2020-02-27
356   2019-11-14
357   2019-04-10
358   2021-12-10
359   2020-07-27
360   2021-11-12
361   2020-07-13
362   2020-07-13
363   2020-07-01
364   2019-03-29
365   2021-03-04
366   2021-03-17
367   2020-09-10
368   2021-09-17
369   2021-12-15
370   2019-09-05
371   2020-02-27
372   2019-02-22
373   2019-10-15
374   2019-10-15
375   2019-10-30
376   2019-10-18
377   2021-10-20
378   2020-10-23
379   2019-01-25
380   2019-05-21
381   2019-04-10
382   2020-06-09
383   2021-10-09
384   2019-07-31
385   2021-09-08
386   2019-02-26
387   2019-04-09
388   2020-07-30
389   2019-01-07
390   2019-10-17
391   2020-08-21
392   2019-04-23
393   2019-03-28
394   2019-04-18
395   2020-01-06
396   2019-03-12
397   2019-09-09
398   2019-06-03
399   2019-03-01
400   2020-08-05
401   2021-09-30
402   2020-09-14
403   2019-09-17
404   2019-02-05
405   2019-01-04
406   2019-06-21
407   2020-10-28
408   2020-09-08
409   2020-05-13
410   2019-12-11
411   2020-09-21
412   2019-06-06
413   2020-02-11
414   2019-11-26
415   2020-05-20
416   2020-02-20
417   2020-08-24
418   2019-03-06
419   2019-04-22
420   2020-07-01
421   2019-02-25
422   2019-02-19
423   2019-12-05
424   2020-06-29
425   2019-04-08
426   2019-04-08
427   2019-01-17
428   2019-01-11
429   2020-01-23
430   2019-01-09
431   2020-06-11
432   2021-12-10
433   2019-09-11
434   2020-06-30
435   2020-02-27
436   2019-07-02
437   2019-09-25
438   2020-12-18
439   2019-01-09
440   2019-10-15
441   2021-01-25
442   2019-08-06
443   2019-11-25
444   2019-01-31
445   2019-08-06
446   2019-07-09
447   2019-01-09
448   2020-01-22
449   2019-08-20
450   2019-07-29
451   2021-02-09
452   2021-05-17
453   2020-06-29
454   2019-07-31
455   2019-08-15
456   2020-01-14
457   2020-07-14
458   2019-08-13
459   2019-03-14
460   2019-09-19
461   2019-09-17
462   2019-03-29
463   2019-03-18
464   2019-09-04
465   2020-01-14
466   2019-05-24
467   2020-05-19
468   2019-04-05
469   2019-09-06
470   2019-02-28
471   2019-04-29
472   2019-02-13
473   2020-08-25
474   2019-05-16
475   2019-05-30
476   2020-12-02
477   2020-04-06
478   2021-02-01
479   2020-01-10
480   2019-06-28
481   2020-05-12
482   2019-04-25
483   2019-02-22
484   2020-11-24
485   2019-12-27
486   2019-04-03
487   2019-12-06
488   2019-07-29
489   2019-03-28
490   2020-06-18
491   2019-04-16
492   2019-03-04
493   2019-04-19
494   2019-07-10
495   2019-10-11
496   2020-07-21
497   2019-06-05
498   2019-08-21
499   2019-07-18
500   2019-09-12
501   2019-12-11
502   2019-11-01
503   2019-03-15
504   2019-08-20
505   2019-09-23
506   2020-02-19
507   2020-03-05
508   2019-11-18
509   2020-08-25
510   2019-10-31
511   2020-03-27
512   2020-03-16
513   2020-02-18
514   2019-09-12
515   2020-03-30
516   2020-09-21
517   2020-11-03
518   2019-10-28
519   2019-09-20
520   2020-01-28
521   2019-11-27
522   2020-12-03
523   2019-03-13
524   2020-07-14
525   2021-08-05
526   2021-08-31
527   2020-01-17
528   2020-10-01
529   2020-01-07
530   2020-12-05
531   2021-08-04
532   2020-02-10
533   2021-10-08
534   2021-11-03
535   2019-10-18
536   2020-01-21
537   2020-05-04
538   2021-03-04
539   2019-09-17
540   2019-08-14
541   2021-10-19
542   2019-10-02
543   2020-03-03
544   2019-09-11
545   2020-03-24
546   2019-09-17
547   2019-09-17
548   2021-03-26
549   2020-05-18
550   2020-01-10
551   2019-06-28
552   2020-01-03
553   2020-02-03
554   2021-11-24
555   2020-12-11
556   2021-06-09
557   2019-10-22
558   2020-11-05
559   2019-11-21
560   2020-06-22
561   2020-03-16
562   2019-08-30
563   2020-02-03
564   2020-09-21
565   2019-12-10
566   2020-03-05
567   2019-11-07
568   2020-08-24
569   2021-03-23
570   2021-03-30
571   2020-01-14
572   2020-03-06
573   2021-12-06
574   2019-11-22
575   2020-03-06
576   2020-09-21
577   2020-10-02
578   2020-07-13
579   2021-02-11
580   2020-05-05
581   2020-02-07
582   2021-01-29
583   2020-12-16
584   2021-01-14
585   2020-09-11
586   2021-01-08
587   2020-05-13
588   2021-09-09
589   2020-09-15
590   2021-03-17
591   2021-01-08
592   2020-10-30
593   2021-01-15
594   2020-01-08
595   2020-05-28
596   2020-05-27
597   2019-11-04
598   2020-07-27
599   2020-06-11
600   2021-12-13
601   2020-01-03
602   2020-05-18
603   2021-02-25
604   2020-03-06
605   2021-11-17
606   2021-04-19
607   2021-03-05
608   2020-09-17
609   2021-06-07
610   2020-03-05
611   2020-09-24
612   2020-08-24
613   2020-12-01
614   2020-10-05
615   2020-02-19
616   2020-05-04
617   2020-09-23
618   2020-05-04
619   2021-07-29
620   2020-11-18
621   2021-01-13
622   2020-12-04
623   2020-12-02
624   2020-12-21
625   2020-11-19
626   2020-02-13
627   2020-01-16
628   2020-06-30
629   2020-03-03
630   2020-08-04
631   2021-02-05
632   2020-12-29
633   2020-07-16
634   2021-03-01
635   2020-07-10
636   2020-06-25
637   2021-06-28
638   2021-01-26
639   2021-08-27
640   2020-07-23
641   2020-11-13
642   2021-06-15
643   2021-04-05
644   2020-09-24
645   2021-10-26
646   2021-09-13
647   2021-09-15
648   2021-08-20
649   2020-12-22
650   2020-07-13
651   2020-12-17
652   2020-08-19
653   2020-11-18
654   2021-01-26
655   2021-04-15
656   2020-07-24
657   2021-11-23
658   2020-12-17
659   2021-03-17
660   2021-01-28
661   2020-10-20
662   2021-01-12
663   2020-10-02
664   2020-12-14
665   2021-04-22
666   2021-03-03
667   2021-02-17
668   2021-10-28
669   2021-06-23
670   2021-08-13
671   2021-04-20
672   2020-11-25
673   2021-07-09
674   2021-08-12
675   2020-10-01
676   2021-01-14
677   2021-04-09
678   2021-12-11
679   2021-11-17
680   2020-12-23
681   2021-11-23
682   2021-02-05
683   2021-05-26
684   2021-02-04
685   2021-10-04
686   2021-06-11
687   2021-09-07
688   2021-05-21
689   2021-01-12
690   2021-10-22
691   2021-10-20
692   2021-05-20
693   2021-09-30
694   2021-11-04
695   2021-11-24
696   2021-12-17
Name: Fully Permitted, dtype: datetime64[ns]

In [13]:
start_date = "2019-01-01"

In [14]:
end_date = "2021-12-31"

In [15]:
after_start_date = df["Fully Permitted"] >= start_date

In [16]:
before_end_date = df["Fully Permitted"] <= end_date

In [17]:
between_two_dates = after_start_date & before_end_date

In [18]:
filtered_dates = df.loc[between_two_dates]

In [19]:
filtered_dates.head()

,Job #,Borough,House #,Street Name,Job Type,Job Status,Job Status Descrp,Latest Action Date,Building Type,Community - Board,Applicant's First Name,Applicant's Last Name,Applicant Professional Title,Applicant License #,Professional Cert,Fully Permitted,Existing Zoning Sqft,Proposed Zoning Sqft,ExistingNo. of Stories,Proposed No. of Stories,Existing Height,Proposed Height,Owner's First Name,Owner's Last Name,Owner's Business Name,City,Owner'sPhone #,Job Description,DOBRunDate,JOB_S1_NO,GIS_LATITUDE,GIS_LONGITUDE,GIS_NTA_NAME
0,220538611,BRONX,915,ELSMERE PL,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/05/2021,OTHERS,206,MINKUK,KIM,RA,32897,N,2021-04-29,0,49075,0,9,0,90,JAY,MARTINO,STAGG GROUP,NaN,9146687511,ERECTION OF 9 STORY RESIDENTIAL BUILDING.,11/23/2021 00:00:00,2637000,40.841590,-73.885100,East Tremont
1,220152803,BRONX,1325,SOUTHERN BOULEVARD,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/15/2021,OTHERS,203,SUZANNA,THARIAN,RA,29684,N,2019-03-07,0,34363,0,8,0,85,NORBERTO,VELAZQUEZ,1319-25 SOUTHERN BLVD LLC,NaN,3475655481,NaN,11/16/2021 00:00:00,2802048,40.831084,-73.891496,Crotona Park East
2,220649706,BRONX,3923,CARPENTER AVE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,04/29/2021,OTHERS,212,JULIO,LEDER-LUIS,RA,20478,N,2021-03-16,0,20237,0,7,0,65,ROBERT,LUMAJ,ATLANTIS RENOVATIONS INC,NaN,3476210292,NaN,04/30/2021 00:00:00,2965629,40.887420,-73.864069,Williamsbridge-Olinville
3,121205604,MANHATTAN,270,PARK AVENUE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/30/2021,OTHERS,105,NICKOLAS,ZIGOMANIS,RA,33081,N,2021-11-30,0,1864801,0,57,0,1388,DEVIN,MAHER,"JP MORGAN AND CHASE BANK, N.A.",NaN,2122704958,NaN,12/09/2021 00:00:00,3126397,40.755641,-73.975109,Midtown-Midtown South
4,321597795,BROOKLYN,963,ATLANTIC AVENUE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,06/22/2021,OTHERS,302,DANIEL,BERNSTEIN,RA,16854,N,2021-06-22,0,88368,0,9,0,95,EFRAIM,WEBER,86 LEFFERTS CORP,NaN,9176824871,NaN,10/12/2021 00:00:00,3158207,40.680263,-73.960337,Clinton Hill

In [20]:
index = filtered_dates.index
number_of_rows = len(index)
print(number_of_rows)

697

In [32]:
import csv

In [33]:
filtered_dates.to_csv('DOB_Job_App_Filings_2019_2021.csv')

In [21]:
proposed_over_ten = filtered_dates['Proposed No. of Stories'] >= 10

In [23]:
job_market_19_21_10_plus = filtered_dates.loc[proposed_over_ten]

In [24]:
job_market_19_21_10_plus.head()

,Job #,Borough,House #,Street Name,Job Type,Job Status,Job Status Descrp,Latest Action Date,Building Type,Community - Board,Applicant's First Name,Applicant's Last Name,Applicant Professional Title,Applicant License #,Professional Cert,Fully Permitted,Existing Zoning Sqft,Proposed Zoning Sqft,ExistingNo. of Stories,Proposed No. of Stories,Existing Height,Proposed Height,Owner's First Name,Owner's Last Name,Owner's Business Name,City,Owner'sPhone #,Job Description,DOBRunDate,JOB_S1_NO,GIS_LATITUDE,GIS_LONGITUDE,GIS_NTA_NAME
3,121205604,MANHATTAN,270,PARK AVENUE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/30/2021,OTHERS,105,NICKOLAS,ZIGOMANIS,RA,33081,N,2021-11-30,0,1864801,0,57,0,1388,DEVIN,MAHER,"JP MORGAN AND CHASE BANK, N.A.",NaN,2122704958,NaN,12/09/2021 00:00:00,3126397,40.755641,-73.975109,Midtown-Midtown South
6,210182283,BRONX,2351,WALTON AVENUE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,10/14/2021,OTHERS,205,DAVID,GROSS,RA,16587,N,2021-10-14,0,28585,0,12,0,114,STEVEN,MOUNT,2351 WALTON OWNER LLC,NaN,9172177359,NaN,10/15/2021 00:00:00,3270079,40.859644,-73.902027,Fordham South
8,121187802,MANHATTAN,145,WEST 47 ST,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/05/2021,OTHERS,105,JONATHAN,MOSS,RA,25207,N,2019-02-11,0,263586,0,48,0,509,DAVID,WROBEL,CLARITY 47 LLC,NaN,2124218100,NaN,12/28/2021 00:00:00,2765418,40.758577,-73.983100,Midtown-Midtown South
10,321588545,BROOKLYN,34,UNION AVE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,04/30/2021,OTHERS,301,FARIBA,MAKOOI,RA,34686,N,2021-04-30,0,423295,0,12,0,114,SIMON,DUSHINSKY,HARRISON REALTY LLC,NaN,7182464762,NaN,10/06/2021 00:00:00,3193905,40.700831,-73.950274,Bedford
16,320978064,BROOKLYN,2286,CROPSEY AVENUE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,12/21/2020,OTHERS,311,MICHAEL,KANG,RA,24849,N,2020-12-21,0,241259,0,23,0,240,MENG HUA,WANG,CROPSEY PARTNERS LLC.,NaN,7189391002,NaN,05/04/2021 00:00:00,2354982,40.595843,-73.997001,Bensonhurst West

In [25]:
index = job_market_19_21_10_plus.index
number_of_rows = len(index)
print(number_of_rows)

267

In [26]:
proposed_over_seven = filtered_dates['Proposed No. of Stories'] >= 7

In [27]:
proposed_under_nine = filtered_dates['Proposed No. of Stories'] <= 9

In [28]:
btwn_seven_and_nine = proposed_over_seven & proposed_under_nine

In [29]:
job_market_19_21_btwn_7_and_9 = filtered_dates.loc[btwn_seven_and_nine]

In [30]:
index = job_market_19_21_btwn_7_and_9.index
number_of_rows = len(index)
print(number_of_rows)

430

In [31]:
job_market_19_21_btwn_7_and_9.head()

,Job #,Borough,House #,Street Name,Job Type,Job Status,Job Status Descrp,Latest Action Date,Building Type,Community - Board,Applicant's First Name,Applicant's Last Name,Applicant Professional Title,Applicant License #,Professional Cert,Fully Permitted,Existing Zoning Sqft,Proposed Zoning Sqft,ExistingNo. of Stories,Proposed No. of Stories,Existing Height,Proposed Height,Owner's First Name,Owner's Last Name,Owner's Business Name,City,Owner'sPhone #,Job Description,DOBRunDate,JOB_S1_NO,GIS_LATITUDE,GIS_LONGITUDE,GIS_NTA_NAME
0,220538611,BRONX,915,ELSMERE PL,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/05/2021,OTHERS,206,MINKUK,KIM,RA,32897,N,2021-04-29,0,49075,0,9,0,90,JAY,MARTINO,STAGG GROUP,NaN,9146687511,ERECTION OF 9 STORY RESIDENTIAL BUILDING.,11/23/2021 00:00:00,2637000,40.841590,-73.885100,East Tremont
1,220152803,BRONX,1325,SOUTHERN BOULEVARD,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/15/2021,OTHERS,203,SUZANNA,THARIAN,RA,29684,N,2019-03-07,0,34363,0,8,0,85,NORBERTO,VELAZQUEZ,1319-25 SOUTHERN BLVD LLC,NaN,3475655481,NaN,11/16/2021 00:00:00,2802048,40.831084,-73.891496,Crotona Park East
2,220649706,BRONX,3923,CARPENTER AVE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,04/29/2021,OTHERS,212,JULIO,LEDER-LUIS,RA,20478,N,2021-03-16,0,20237,0,7,0,65,ROBERT,LUMAJ,ATLANTIS RENOVATIONS INC,NaN,3476210292,NaN,04/30/2021 00:00:00,2965629,40.887420,-73.864069,Williamsbridge-Olinville
4,321597795,BROOKLYN,963,ATLANTIC AVENUE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,06/22/2021,OTHERS,302,DANIEL,BERNSTEIN,RA,16854,N,2021-06-22,0,88368,0,9,0,95,EFRAIM,WEBER,86 LEFFERTS CORP,NaN,9176824871,NaN,10/12/2021 00:00:00,3158207,40.680263,-73.960337,Clinton Hill
5,321941182,BROOKLYN,1882,BROADWAY,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,05/05/2021,OTHERS,316,JEFFREY,KAMEN,RA,23279,N,2021-05-05,0,63644,0,7,0,70,YISROEL,GREENFELD,BROADWAY 1884 LLC,NaN,3476755480,NaN,01/05/2022 00:00:00,3161454,40.680622,-73.906490,Ocean Hill

In [75]:
proposed_over_seven = filtered_dates['Proposed No. of Stories'] >= 7

In [76]:
#exisiting_over_seven = filtered_dates['ExistingNo. of Stories'] >= 7

In [77]:
#over_seven = proposed_over_seven & exisiting_over_seven

In [78]:
job_market_19_21 = filtered_dates.loc[proposed_over_seven]

In [79]:
job_market_19_21.head()

,Job #,Borough,House #,Street Name,Job Type,Job Status,Job Status Descrp,Latest Action Date,Building Type,Community - Board,Applicant's First Name,Applicant's Last Name,Applicant Professional Title,Applicant License #,Professional Cert,Fully Permitted,Existing Zoning Sqft,Proposed Zoning Sqft,ExistingNo. of Stories,Proposed No. of Stories,Existing Height,Proposed Height,Owner's First Name,Owner's Last Name,Owner's Business Name,City,Owner'sPhone #,Job Description,DOBRunDate,JOB_S1_NO,GIS_LATITUDE,GIS_LONGITUDE,GIS_NTA_NAME
0,220538611,BRONX,915,ELSMERE PL,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/05/2021,OTHERS,206,MINKUK,KIM,RA,32897,N,2021-04-29,0,49075,0,9,0,90,JAY,MARTINO,STAGG GROUP,NaN,9146687511,ERECTION OF 9 STORY RESIDENTIAL BUILDING.,11/23/2021 00:00:00,2637000,40.841590,-73.885100,East Tremont
1,220152803,BRONX,1325,SOUTHERN BOULEVARD,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/15/2021,OTHERS,203,SUZANNA,THARIAN,RA,29684,N,2019-03-07,0,34363,0,8,0,85,NORBERTO,VELAZQUEZ,1319-25 SOUTHERN BLVD LLC,NaN,3475655481,NaN,11/16/2021 00:00:00,2802048,40.831084,-73.891496,Crotona Park East
2,220649706,BRONX,3923,CARPENTER AVE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,04/29/2021,OTHERS,212,JULIO,LEDER-LUIS,RA,20478,N,2021-03-16,0,20237,0,7,0,65,ROBERT,LUMAJ,ATLANTIS RENOVATIONS INC,NaN,3476210292,NaN,04/30/2021 00:00:00,2965629,40.887420,-73.864069,Williamsbridge-Olinville
3,121205604,MANHATTAN,270,PARK AVENUE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,11/30/2021,OTHERS,105,NICKOLAS,ZIGOMANIS,RA,33081,N,2021-11-30,0,1864801,0,57,0,1388,DEVIN,MAHER,"JP MORGAN AND CHASE BANK, N.A.",NaN,2122704958,NaN,12/09/2021 00:00:00,3126397,40.755641,-73.975109,Midtown-Midtown South
4,321597795,BROOKLYN,963,ATLANTIC AVENUE,NB,R,PERMIT ISSUED - ENTIRE JOB/WORK,06/22/2021,OTHERS,302,DANIEL,BERNSTEIN,RA,16854,N,2021-06-22,0,88368,0,9,0,95,EFRAIM,WEBER,86 LEFFERTS CORP,NaN,9176824871,NaN,10/12/2021 00:00:00,3158207,40.680263,-73.960337,Clinton Hill

In [81]:
index = job_market_19_21.index
number_of_rows = len(index)
print(number_of_rows)

697

In [82]:
import csv

In [83]:
job_market_19_21.to_csv('job_market_19_21.csv')

In [84]:
#Include another filter for between 7 and 9 inclusive vs 10 stories and above.

In [85]:
#We want our main findings to end up being: 

#In 2019 we increaesed the market share by x
#In 2020 we increased the market share by x 
#In 2021 we increased the market share by x

In [86]:
#Prior to legislation the total market share would have been buildings 10 stories and above 
#Post legislation, the market share includes buildings 7 to 9.

In [ ]:
#Potential clients for the new market are in 2022. 
#Rule change, safety coordinator from 6-10 and need a super from 10 and above.